/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_firstjni_NativeInvokeJava */

#ifndef _Included_com_example_firstjni_NativeInvokeJava
#define _Included_com_example_firstjni_NativeInvokeJava
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_firstjni_NativeInvokeJava
 * Method:    invokeJava
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_firstjni_NativeInvokeJava_invokeJava
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
